#!/usr/bin/env node
// Generates src/deviceParams.ts from src/deviceBanks.yaml
// Run: node scripts/generateDeviceParams.js
// Watch: node scripts/generateDeviceParams.js --watch

const fs = require('fs')
const path = require('path')
const yaml = require('js-yaml')

const yamlPath = path.join(__dirname, '..', 'src', 'deviceBanks.yaml')
const outPath = path.join(__dirname, '..', 'src', 'deviceParams.ts')

const MAX_DEVICES = ['MxDeviceInstrument', 'MxDeviceAudioEffect', 'MxDeviceMidiEffect']

function generate() {
  const devices = yaml.load(fs.readFileSync(yamlPath, 'utf8'))

  const lines = [
    '// AUTO-GENERATED from src/deviceBanks.yaml by scripts/generateDeviceParams.js',
    '// Do not edit this file directly — edit deviceBanks.yaml and run:',
    '//   node scripts/generateDeviceParams.js',
    '',
  ]

  lines.push('export const DEVICE_DICT: Record<string, string[][]> = {')
  for (const device of Object.keys(devices)) {
    const banks = devices[device]
    const bankEntries = Object.values(banks)
    const arrayStr = bankEntries
      .map((params) => {
        const paramStrs = params.map((p) => `'${String(p).replace(/'/g, "\\'")}'`)
        return `[${paramStrs.join(', ')}]`
      })
      .join(', ')
    lines.push(`  ${device}: [${arrayStr}],`)
  }
  lines.push('}')
  lines.push('')

  lines.push('export const BANK_NAME_DICT: Record<string, string[]> = {')
  for (const device of Object.keys(devices)) {
    const banks = devices[device]
    const names = Object.keys(banks).map((n) => `'${n.replace(/'/g, "\\'")}'`)
    lines.push(`  ${device}: [${names.join(', ')}],`)
  }
  lines.push('}')
  lines.push('')

  lines.push(`export const MAX_DEVICES = [${MAX_DEVICES.map((d) => `'${d}'`).join(', ')}]`)
  lines.push('')

  fs.writeFileSync(outPath, lines.join('\n'))
  console.log(`Generated ${outPath} (${Object.keys(devices).length} devices)`)
}

generate()

if (process.argv.includes('--watch')) {
  let timeout = null
  fs.watch(yamlPath, () => {
    if (timeout) clearTimeout(timeout)
    timeout = setTimeout(() => {
      console.log('deviceBanks.yaml changed, regenerating...')
      try {
        generate()
      } catch (e) {
        console.error('Generation failed:', e.message)
      }
    }, 100)
  })
  console.log(`Watching ${yamlPath} for changes...`)
}
