#!/usr/bin/env node
// Generates src/deviceParams.ts from src/deviceBanks.yaml
// Run: node scripts/generateDeviceParams.js
// Watch: node scripts/generateDeviceParams.js --watch

const fs = require('fs')
const path = require('path')

const yamlPath = path.join(__dirname, '..', 'src', 'deviceBanks.yaml')
const outPath = path.join(__dirname, '..', 'src', 'deviceParams.ts')

const MAX_DEVICES = ['MxDeviceInstrument', 'MxDeviceAudioEffect', 'MxDeviceMidiEffect']

function generate() {
  const yaml = fs.readFileSync(yamlPath, 'utf8')

  // Simple YAML parser for our known structure:
  //   DeviceName:
  //     BankName:
  //       - param
  //       - "quoted param"
  const devices = {}
  let currentDevice = null
  let currentBank = null

  for (const rawLine of yaml.split('\n')) {
    if (rawLine.startsWith('#') || rawLine.trim() === '') continue

    const indent = rawLine.length - rawLine.trimStart().length
    const line = rawLine.trim()

    if (indent === 0 && line.endsWith(':')) {
      currentDevice = line.slice(0, -1)
      devices[currentDevice] = {}
      currentBank = null
    } else if (indent === 2 && line.endsWith(':')) {
      let bankName = line.slice(0, -1)
      if (bankName.startsWith('"') && bankName.endsWith('"')) {
        bankName = bankName.slice(1, -1)
      }
      currentBank = bankName
      devices[currentDevice][currentBank] = []
    } else if (indent === 4 && line.startsWith('- ')) {
      let val = line.slice(2)
      if (val.startsWith('"') && val.endsWith('"')) {
        val = val.slice(1, -1)
      }
      devices[currentDevice][currentBank].push(val)
    }
  }

  // Generate TypeScript
  const lines = [
    '// AUTO-GENERATED from src/deviceBanks.yaml by scripts/generateDeviceParams.js',
    '// Do not edit this file directly — edit deviceBanks.yaml and run:',
    '//   node scripts/generateDeviceParams.js',
    '',
  ]

  lines.push('export const DEVICE_DICT: Record<string, string[][]> = {')
  for (const device of Object.keys(devices)) {
    const banks = devices[device]
    const bankEntries = Object.values(banks)
    const arrayStr = bankEntries
      .map((params) => {
        const paramStrs = params.map((p) => `'${p.replace(/'/g, "\\'")}'`)
        return `[${paramStrs.join(', ')}]`
      })
      .join(', ')
    lines.push(`  ${device}: [${arrayStr}],`)
  }
  lines.push('}')
  lines.push('')

  lines.push('export const BANK_NAME_DICT: Record<string, string[]> = {')
  for (const device of Object.keys(devices)) {
    const banks = devices[device]
    const names = Object.keys(banks).map((n) => `'${n.replace(/'/g, "\\'")}'`)
    lines.push(`  ${device}: [${names.join(', ')}],`)
  }
  lines.push('}')
  lines.push('')

  lines.push(`export const MAX_DEVICES = [${MAX_DEVICES.map((d) => `'${d}'`).join(', ')}]`)
  lines.push('')

  fs.writeFileSync(outPath, lines.join('\n'))
  console.log(`Generated ${outPath} (${Object.keys(devices).length} devices)`)
}

generate()

if (process.argv.includes('--watch')) {
  let timeout = null
  fs.watch(yamlPath, () => {
    // Debounce rapid changes
    if (timeout) clearTimeout(timeout)
    timeout = setTimeout(() => {
      console.log('deviceBanks.yaml changed, regenerating...')
      try {
        generate()
      } catch (e) {
        console.error('Generation failed:', e.message)
      }
    }, 100)
  })
  console.log(`Watching ${yamlPath} for changes...`)
}
